### ISSUE TITLE
404 error with some of the download links.

### ISSUE THREAD

**Issue by DarkS293** [arasyi/KissAnime-DTA#1]
Dear arasyi,

*Edit* After looking at it carefully it seems to be caused by hyphens (-) being read as breaks for some reason. If you look at the download links provided by them all the ones that don't work have hyphens which are being replaced by breaks.

Some of the links generated by the "Get Download Links!" button direct to a 404'd page.
I believe this is caused by the inclusion of <br>'s in the generated download link that do not show up on the links that do not result in a 404.

Examples:
http://kissanime.com/Anime/Saint-Seiya-The-Hades-Chapter-Sanctuary - the links generated for episodes 2-5, 8, 9, 11 and 12.

http://kissanime.com/Anime/Hunter-x-Hunter-2011 - the links generated for episodes 143-146 and others.

Example generated 404 links vs working links: 
(404) Saint Seiya: The Hades Chapter - Sanctuary Episode 002: https://2.bp.blogspot.com/h5QQy_DP36g_GpyFm%3Cbr%3EuSKrOXyN4xNXNkbXbd_9%3Cbr%3EF2n4=m22

(Working) Saint Seiya: The Hades Chapter - Sanctuary Episode 002: https://2.bp.blogspot.com/CTD2950ya0Ugol4B__dwdLh7rAuvbdVKBBwkqwR_wTo=m22

(404) Hunter x Hunter (2011) Episode 148: https://2.bp.blogspot.com/6V9lKK72SGt39kGr0ZNmp%3Cbr%3Ef4fW%3Cbr%3Et6pjaPwagwrnqEw=m22

(Working) Hunter x Hunter (2011) Episode 147: https://2.bp.blogspot.com/ZaaJsTYoP4QdJZrcMgOAs_ngjRoDMpPHUbk4qeDM8Q=m22

If you need more examples I'd be happy to provide them besides these cases I encountered it works flawlessly I really appreciate you writing this up. Let me know if there's anything I can do to help.

Regards,
Dark

**Comment by arasyi** [comment]
Thanks. Will check it soon
