### ISSUE TITLE
Kissanime new captcha feature.

### ISSUE THREAD

**Issue by mysticpoisen** [arasyi/KissAnime-DTA#5]
Hi there! Me again, script is working correctly, but as I'm sure you know, Kissanime now utilizes a recaptcha so it is difficult to get entire series at once. Perhaps a feature to grab links from only certain episodes, or even persistence to allow you to manually activate the recaptcha while the script runs and grabs the links.

**Comment by arasyi** [comment]
I don't see any captcha here.
Could you give me some more detail on that?

**Comment by mysticpoisen** [comment]
Well now, that's odd. For a bit there, it would give me a recaptcha when clicking on an episode. It would be good for about 15 episodes, and then another captha would be required. Without it, the script would not get any links

But now, it seems that it just went away. Possibly them testing things, maybe something on my end. Ether way, seems to be gone now.

**Comment by moisesnake** [comment]
this is still an issue  , at the very least when I try to use it on kisscartoon, I dont regularly download from the cartoon site so not a huge problem, but they might have or in the future implement the same on KA.
